### ISSUE TITLE
chain() renaming?

### ISSUE THREAD

**Issue by dankelley** [dankelley/mooring#20]
The screenshot below (see the bottom part, the mooring diagram) indicates that 5/8 chain should not be of a standard 1-m length.  This means -- I now propose -- that this element should be in a category that stores buoyancy as `buoyancyPerMeter`.

I'm using this word `chain()` because that's what Dewey uses.  But, frankly, I don't like it much, because it includes things like swivels and such, that I don't regard as chains.

I think it might make sense to move chains into `wire()`, with the rule being that it stores things that indicate buoyancy as kg/m, not kg, and that have a meaning for a `length` argument.

Or, I could make a category that is *only* chains, and put those other things like swivels somewhere else.

I have some meetings coming up but I'll think about this later.

<img width="818" alt="Screen Shot 2021-06-08 at 12 45 46 PM" src="https://user-images.githubusercontent.com/99469/121216788-9a37f300-c857-11eb-9961-73eff504e18a.png">

**Comment by dankelley** [comment]
I'm moving the BIO `5/8in galvanized chain` to 'wire', as you can see in this edit.  The other BIO things seem to be discrete, so they belong together ... but I don't know if they are called "chains".  I think "hardware" might be a better name.

<img width="778" alt="Screen Shot 2021-06-08 at 1 31 39 PM" src="https://user-images.githubusercontent.com/99469/121223407-e25a1400-c85d-11eb-97e2-ad1366a1a472.png">

**Comment by dankelley** [comment]
@clayton33, @richardsc and @formulafunracing - what do you think about calling swivels, shackles, etc as `hardware`?  I want to use `chain` to mean things whose mass is defined per unit length, and `hardware` (or some other name) for things with discrete masses.

**Comment by FormulaFunRacing** [comment]
Hardware sounds fine.  If I remember correctly other programs call them 'connectors', but they have a standard set of characteristics.

**Comment by clayton33** [comment]
I trust whatever @FormulaFunRacing says.

**Comment by dankelley** [comment]
I like `connectors` for swivels and shackels, etc.  The main one I see in https://dankelley.github.io/mooring/articles/mooring_elements.html#chain-characteristics-1
that doesn't seem to quite be a connector is a `ballast weight`.  But, I could leave it there, or make a new category called `misc` or something.

PS. I am going to make a function to look things up.  It would take a character argument and then it would do a fuzzy search on it, in the names of all the `wire` types, and then the `float` types etc, and spit out some suggestions, like `lookup("3/8")` might spit back suggestions, with code like
```R
> C<-chain("?"); C[grep("3/8", sapply(C, \(x) chain(x)$model))]
[1] "1/2in shac+3/8in shac" "3/8in buoy chain"     
[3] "3/8in chain SL"        "3/8in shackle"   
```
although of course I'll also look up wires and all the other things, and give specific suggestions like maybe:
```R
chain("1/2in shac+3/8in shac")
chain("3/8in buoy chain")
```
and so forth.

**Comment by dankelley** [comment]
Another Q for anyone willing to help: what do "SS" and "SL" mean, in some items?  I see them in the Dewey data (https://dankelley.github.io/mooring/articles/mooring_elements.html#chain-characteristics-1) and am trying to figure out whether I want to chop his data into two parts: 
* chain things (e.g. the first item, `1/2in buoy chain` seems like a chain to me.
* connector things

Basically, the pattern is that he seems to list height as 1 for things that I will call chains (e.g. item 1 in that list), and other values for things I'll call connectors (e.g. item 4 in the list)

I'm rambling a bit in the heat here, I know, but my main question is what LL, SL and SS mean.  It's just for curiosity, actually.

**Comment by FormulaFunRacing** [comment]
I'm going to take a guess, but LL, SL and SS might be the characteristics of the connection between components (line to line, solid to line and solid to solid).

**Comment by dankelley** [comment]
Oh, that makes some sense.  Thanks, @FormulaFunRacing !

**Comment by dankelley** [comment]
I've created a new "connector" type, and put some things there.  This involved some other things, like storing `buoyancyPerMeter` instead of `buoyancy` for chain objects but all seems to be working (at least passing built-in tests) so far.  See 
https://dankelley.github.io/mooring/articles/mooring_elements.html#chain-characteristics-1
for the chain type, and
https://dankelley.github.io/mooring/articles/mooring_elements.html#connector-characteristics-1
for the connector type.

I'll close the issue now.

**Comment by FormulaFunRacing** [comment]
Our old TxBuoy is built around this concept--Area per length (m2/m), Weight per length (N/m).

**Comment by dankelley** [comment]
Regarding txBuoy (if that's the source of an excel spreadsheet that I have), do you know what `DRAG-N` and `DRAG-T` mean? I assume it's normal and tangential, and so I could maybe figure out CD values from them, if I knew the area and also the flow speed.

NOTE: this is not critical.  A lot of the elements in that table don't have dimensions listed that let me compute area, anyway.  And I don't think even that is really super-important, because the drag on something small ought to be swamped by the drag on the 500m of wire attached to it, or the great big buoyancy element, etc.

**Comment by FormulaFunRacing** [comment]
Yeah, drag - normal   drag - tangential
