### ISSUE TITLE
need advice on mooring component "syntactic foam float..."

### ISSUE THREAD

**Issue by dankelley** [dankelley/mooring#24]
I'm wondering whether one of my BIO colleagues can help with this (perhaps @formulafunracing or @clayton33?).  

I decided to try to simulate mooring 1840 (Sackville Spur July 2013).  In the details you can see part of the BIO mooring diagram (which I think is available to the above-named colleagues, so I won't post it here), along with my quickly-written R code.  There's also a plot, which can be ignored for now, I think.

The issue is that I had to guess on how to specify some of the elements listed in the diagram.  In some cases, I think my guess will be OK even if a bit wrong (e.g. I think the two styles of microcat will likely have similar effects on drag and buoyancy).  However, I am pretty uncertain also of buoyancy elements, and they are of course crucial to mooring dynamics.  That's what I'm asking about.  In particular:

1. what is the "SYNTACTIC FOAM FLOAT WITH LONG RANGER ADCP..." that's shown in the mooring diagram from the BIO doc?  Is it in the excel file?  If not, can anyone advise me on its buoyancy and area (maybe even CD ... manufacturers tend to list that).
2. what does a "3 GLASS BUB PACKAGES" mean?  Is that three of some kind of package?  If so, what is the buoyancy of that package, etc?  Lacking any idea, really, I just used `float("streamlined bub 3 Viny balls")`.

Any advice would be appreciated.  No rush on this, though.  It's just something I spend a few minutes a day on.

<details>

**Portion of BIO doc**

<img width="776" alt="Screen Shot 2021-06-09 at 8 00 01 AM" src="https://user-images.githubusercontent.com/99469/121343107-b8096480-c8f8-11eb-8eda-2fa5fff3aa04.png">

**R code**

``` r
## Mooring 1840 (p10 of doc)
library(mooring)
# Abbreviations for convenience
W <- function(length) wire("3/16in galvanized wire coated to 1/4in", length=length)
BUB3 <- float("streamlined bub 3 Viny balls")
RCM11 <- instrument("RCM-11 in frame") # "AANDERAA RCM11"
microcat <- instrument("SBE37 microcat clamp-on style") # "SBE MICROCAT"

m <- mooring(anchor(depth=1400),
             chain("5/8in galvanized chain", length=10),
             release("benthos 965a release"),  # dual benthos 965-a
             BUB3,
             W(34),
             microcat,
             RCM11,
             W(50),
             BUB3,
             W(144),
             microcat,
             RCM11,
             W(147),
             BUB3,
             W(46),
             microcat,
             RCM11,
             W(198),
             microcat,
             RCM11,
             W(198),
             microcat,
             RCM11,
             W(197),
             microcat,
             RCM11,
             W(146),
             microcat,
             connector("swivel"),
             connector("ballast", 100/2.2, height=1, width=0.05, CD=1), # guess
             float("syn. float,bracket and 109lb ADCP"), # total guess; lots of choices
             W(149),
             microcat,
             float("streamlined bub 3 Viny balls")) # total guess
md <- discretise(m)
mdk <- knockdown(md, u=function(depth) exp(-depth/1000))
#> Warning in knockdown(md, u = function(depth) exp(-depth/1000)): FIXME: u=function() case is not fully coded yet (no iteration is done)
plot(mdk)
```

![](https://i.imgur.com/RMGgPRU.png)

<sup>Created on 2021-06-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by FormulaFunRacing** [comment]
Hi Dan.  The syntactic float (capsule) and ADCP has a 'length' of 2.42 m and weighs 1740 lbf [7740 N] buoyant.  It has a frontal area of about 1.2342 m2 and a drag - normal of 0.6.  The BUB package is a twin 17" glass sphere package.  it has a 'length' of 1.187 m and weighs 96.5 lbf [429 N] buoyant.  It has a frontal area of 0.5531 m2 and a drag - normal of 1.1.  There are three of these packages, so multiply accordingly.  Hope this helps a bit. - J

**Comment by dankelley** [comment]
Many thanks. What is a "drag normal"?  Is that the CD for horizontal flow?

This is exceptionally helpful.  Thanks!!

**Comment by FormulaFunRacing** [comment]
Yes, for horizontal current flow.  Cheers!

**Comment by dankelley** [comment]
This is **so** much more fun than the meeting I'm in :-)

**Comment by dankelley** [comment]
Many thanks, @FormulaFunRacing, for your patience and generosity!

In "main" branch commit c41d6e9401905e704f84bb19a65d2d39b82dc8d3, I have updated the BIO `float` dataset, based on this new information on what the columns mean.

My procedure is explained in `create_data/bio/README.Rmd` (which is built up into a PDF file using `cd create_data/bio ; make docs`), so I won't go the details here, except to say that we now have proper diameters (which are how this package computes area) and CD values, and my check on the "bub" case gives the stated area=0.5531 m^2  and CD=1.1.

``` r
library(mooring)
f <- float("bub 2x17in glass")
area(f)
#> [1] 0.5528583
CD(f)
#> [1] 1.1
```

<sup>Created on 2021-06-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by dankelley** [comment]
I see that the float I was wondering about is named
`SYN. FLOAT,BRACKET AND 109 LB.ADCP` in the excel file, and 
this is called
```R
float('syn. float,bracket and 109lb ADCP')
```
in the package.  Arguably, I ought to use the `syn.` abbreviation for what the package calls
```R
float('syn. float,bracket and 109lb ADCP')
```

I don't really like inconsistency much, so I think I am going to change the name, to abbreviate both, and not just the one witht the 109lb adcp.  (I see why the excel file abbreviates only the 109lb one, but I change other things for consistency, and so I think I'll change this one, too.

**Comment by dankelley** [comment]
I'm also going to change 
1. a `2 x 17in` text fragment to `2x 17in`, because the other entries there are not putting space before the `x`.
2. `bub` to `BUB`, since that's how @FormulaFunRacing wrote it, and so I assume that's right.
3. `adcp` to `ADCP`

Thus, my csv file reads as follows
```
"name","buoyancy","height","diameter","CD","code","source"
streamlined BUB 2x 17in glass,         45.41, 0.74,  0.455,0.6,NA,"BIO"
a2 package ADCP and 2 Viny balls,      29.08, 0.563, 0.397,0.6,NA,"BIO"
3 pack Viny 12b-3 floats,              57.14, 1,     0.529,1.1,NA,"BIO"
streamlined BUB 3 Viny balls,          52.65, 0.563, 0.397,0.6,NA,"BIO"
BUB 2x17in glass,                      43.78, 1.187, 0.839,1.1,NA,"BIO"
IPS / 2x b3 subs assembly,             78.88, 1,     0.748,0.6,NA,"BIO"
ADCP / 2x c3 subs assembly,            42.24, 1,     0.910,0.6,NA,"BIO"
stablemoor 533lb 3500 msw with ADCP,  192.45, 1.286, 1.727,0.6,NA,"BIO"
stablemoor 1000lb 3500 msw with ADCP, 404.39, 1.286, 1.727,0.6,NA,"BIO"
stablemoor 1015lb 1500 msw with ADCP, 411.22, 1.286, 1.720,0.6,NA,"BIO"
stablemoor 580lb 1500 msw with ADCP,  213.78, 1.286, 1.727,0.6,NA,"BIO"
"syn. float with ADCP bracket",       839.18, 2.42,  1.254,0.6,NA,"BIO"
"syn. float,bracket and 109lb ADCP",  789.80, 2.42,  1.254,0.6,NA,"BIO"
```

**Comment by dankelley** [comment]
Possibly I should change `subs` to `SUBS`?

My rule is that I want to use upper-case for acronyms, but lower case for other things, including company names.  (Some companies do weird things with names, e.g. S. Jobs made that NeXT company...)

**Comment by dankelley** [comment]
Since the question, as posed in the title, has been answered, I'm closing this issue now.  Of course, I might change `subs` to `SUBS` later on, if someone advises that this would be sensible.

**Comment by dankelley** [comment]
Thanks for that, J.  I'll take a look at editing names tomorrow.  Things have got easier now that a person can do e.g.

``` r
library(mooring)
float("?bub")
#> Some possible matches:
#>      float('ADCP / 2x c3 subs assembly') 
#>      float('BUB 2x17in glass') 
#>      float('Double 16in Viny') 
#>      float('Double 17in') 
#>      float('IPS / 2x b3 subs assembly') 
#>      float('streamlined BUB 2x 17in glass') 
#>      float('streamlined BUB 3 Viny balls')
```
but, looking at the output, it's wonky.  I see I have "Double" which should be "double".   And if I do BUB for bub, I guess i need to do SUBS for subs.

And then we get to manufacturer names.  That's even worse (`StableMoor` and `DeepWater` make sense, but what if some manufacturer brands a wave into their name for a cute effect...).

I will look at this again tomorrow.  Luckily this package is very much in the development phase, so there's a chance to rename things to make it easier for the user.  My present thinking -- and I know this is 2 steps back after 1 step forward -- is to go to lower-case throughout.  That's a simple rule, and it's easy to type.  Plus, in the `oce` package, we use lower-case for objects, e.g. `adv` for what in a paper I'd write `ADV` ... same for the `ctd` class, for CTD data.

**Comment by FormulaFunRacing** [comment]
A photo is worth a thousand words.  Here are two BUB packages on a pallet.  One BUB has two Benthos 17" glass spheres within protective plastic enclosures mounted to a 4' stainless steel bar.  


![image](https://user-images.githubusercontent.com/85239787/121525227-76e38400-c9ce-11eb-86ed-d937eecd1846.png)

**Comment by dankelley** [comment]
Oh, I love a photo!  Thanks for that.

Is "BUB" an acronym for something?  (Apologies if I already asked that.)

**Comment by clayton33** [comment]
@dankelley see one of @FormulaFunRacing comments above ...

**Comment by dankelley** [comment]
@clayton33 -- I knew your eyes were better than mine.  And I didn't even stare at the eclipse this morning ... just took this photo of the pinhole-camera projection on my wall.  I think that bright line in the middle is because of some refraction going on, because this was through a window with a screen on it.

<img width="225" alt="Screen Shot 2021-06-10 at 9 47 00 AM" src="https://user-images.githubusercontent.com/99469/121527478-d5116680-c9d0-11eb-981f-19cc40ba204e.png">

**Comment by FormulaFunRacing** [comment]
Nice photo, Dan.  Heh...I used a cardboard wine bottle box and a corkscrew to do the same for my daughter.  I must admit, I did have a quick look at the sun with my eyes...LOL.

**Comment by dankelley** [comment]
Hm...the float names from BIO are now as follows. I think maybe "trpl" stands for "triple".  Maybe "tripple" also means "triple"?  Advice on that, @FormulaFunRacing?  I may as well rename now, since my pea-sized brain can remember where I put the files etc.
```
                                   name buoyancy height diameter   CD code source                          originalName
25                            16in Viny    19.00 0.4000   0.4000 0.60    1  Dewey                             16in Viny
22                           17in glass    23.00 0.5700   0.5700 0.95    1  Dewey                           17 in glass
18                             28in ORE   133.00 0.7100   0.7100 0.65    1  Dewey                              28in ORE
3              3 pack Viny 12b-3 floats    57.14 1.0000   0.5290 1.10   NA    BIO              3 pack VINY 12B-3 floats
19                           30in float   160.00 0.7600   0.7600 0.65    1  Dewey                            30in float
17                             37in ORE   300.00 0.9400   0.9400 0.65    1  Dewey                              37in ORE
16                             41in ORE   433.00 1.0400   1.0400 0.65    1  Dewey                              41in ORE
15                             48in ORE   620.00 1.2340   1.2340 0.65    1  Dewey                              48in ORE
32                       54cm Alum CAP3    61.00 0.5500   0.5400 0.65    1  Dewey                        54cm Alum CAP3
33                     54x30inClamShell   405.00 1.4000   0.7500 0.15    1  Dewey                      54x30inClamShell
14                             61in ORE   999.00 1.6500   1.6500 0.65    1  Dewey                              61in ORE
2      a2 package ADCP and 2 Viny balls    29.08 0.5630   0.3970 0.60   NA    BIO      A2 PACKAGE ADCP AND 2 VINY BALLS
7            ADCP / 2x c3 subs assembly    42.24 1.0000   0.9100 0.60   NA    BIO            ADCP / 2x C3 SUBS ASSEMBLY
36                       ADCP FloatTech   460.00 1.4200   1.4200 0.65    1  Dewey                        ADCP FloatTech
24                         BENTHOS 17in    23.00 0.5100   0.5100 0.95    1  Dewey                          BENTHOS 17in
23                        Billings 12in    10.00 0.3430   0.3430 0.95    1  Dewey                         Billings-12in
35                            BPS Float  8000.00 1.5000   0.0000 1.60    1  Dewey                             BPS Float
5                      BUB 2x17in glass    43.78 1.1870   0.8390 1.10   NA    BIO                     BUB  2x17"  GLASS
30                     CDMS 1.2m sphere   682.00 1.2000   1.2000 0.50    1  Dewey                      CDMS 1.2m sphere
31                       CDMS 2m sphere  2470.00 2.0000   2.0000 0.50    1  Dewey                        CDMS 2m sphere
27                     Double 16in Viny    38.00 0.5000   0.6000 0.60    1  Dewey                       Double 16inViny
26                          Double 17in    48.00 0.5000   0.6500 0.95    1  Dewey                           Double 17in
37                      FloatTech CF-12    11.00 0.3000   0.0000 1.00    1  Dewey                       FloatTech CF-12
39                    Geodyn 8ft Toroid  1950.00 0.7620   0.0000 0.65    3  Dewey                      Geodyn 8' Toroid
40                               HMB 20    34.50 0.5080   0.5080 0.65   NA Kelley                                  <NA>
41                               HMB 25    68.50 0.6350   0.6350 0.65   NA Kelley                                  <NA>
42                               HMB 31   141.00 0.7874   0.7874 0.65   NA Kelley                                  <NA>
43                               HMB 36   225.00 0.9144   0.9144 0.65   NA Kelley                                  <NA>
44                               HMB 40   300.00 1.0160   1.0160 0.65   NA Kelley                                  <NA>
45                               HMB 44   413.00 1.1176   1.1176 0.65   NA Kelley                                  <NA>
46                               HMB 49   565.00 1.2446   1.2446 0.65   NA Kelley                                  <NA>
47                               HMB 51   633.00 1.2954   1.2954 0.65   NA Kelley                                  <NA>
48                               HMB 56   831.00 1.4224   1.4224 0.65   NA Kelley                                  <NA>
49                               HMB 62  1122.00 1.5748   1.5748 0.65   NA Kelley                                  <NA>
6             IPS / 2x b3 subs assembly    78.88 1.0000   0.7480 0.60   NA    BIO             IPS / 2x B3 SUBS ASSEMBLY
20                         Kiel SFS40in   320.00 1.0000   1.0000 0.65    1  Dewey                          Kiel SFS40in
9  stablemoor 1000lb 3500 msw with ADCP   404.39 1.2860   1.7270 0.60   NA    BIO Stablemoor 1000 lb 3500 msw with ADCP
10 stablemoor 1015lb 1500 msw with ADCP   411.22 1.2860   1.7200 0.60   NA    BIO Stablemoor 1015 lb 1500 msw with ADCP
8   stablemoor 533lb 3500 msw with ADCP   192.45 1.2860   1.7270 0.60   NA    BIO  Stablemoor 533 lb 3500 msw with ADCP
11  stablemoor 580lb 1500 msw with ADCP   213.78 1.2860   1.7270 0.60   NA    BIO  Stablemoor 580 lb 1500 msw with ADCP
1         streamlined BUB 2x 17in glass    45.41 0.7400   0.4550 0.60   NA    BIO       STREAMLINED BUB  2 x 17"  GLASS
4          streamlined BUB 3 Viny balls    52.65 0.5630   0.3970 0.60   NA    BIO         STREAMLINED BUB  3 VINY BALLS
12         syn. float with ADCP bracket   839.18 2.4200   1.2540 0.60   NA    BIO     SYNTACTIC FLOAT WITH ADCP BRACKET
13   syn. float, bracket and 109lb ADCP   789.80 2.4200   1.2540 0.60   NA    BIO   SYN. FLOAT, BRACKET AND 109 LB.ADCP
34                      Top of Tow Rope     0.01 0.0000   0.0000 0.00    1  Dewey                       Top of Tow Rope
21                      Torp. flt, 3-28   364.00 0.8300   0.8300 0.75    1  Dewey                       Torp. flt, 3-28
38                     Tripple FT CF-12    33.00 0.9000   0.0000 1.00    1  Dewey                      Tripple FT CF-12
29                      Trpl 12in glass    30.00 0.9500   0.6200 1.00    1  Dewey                       Trpl 12in glass
28                       Trpl 16in Viny    56.00 1.5000   0.7500 0.60    1  Dewey                       Trpl 16 in Viny
```

**Comment by dankelley** [comment]
Sorry for last question, @FormulaFunRacing -- I just looked at the "source" column and those really should be questions for Richard Dewey, I think.  But since he has published his software, the names are sort of finalized, so I'll stick with them.

**Comment by FormulaFunRacing** [comment]
'Triple' is a good guess...assuming that the 16" VINY is a model 13B-2 (DIA15.4").  However, each offers 30 kg...much more than the 56 kg shown for a triple assembly.  Hmmm...really heavy mooring rod for them?  Unlikely...

We use the 13.5" model 12B-3 (21 kg) in our shallow SUBS (B3, A2).

![Viny Floats](https://user-images.githubusercontent.com/85239787/121530956-57e7f080-c9d4-11eb-93ec-25454f673823.JPG)

**Comment by dankelley** [comment]
Yes, I agree, that's odd.  I think the "16" in the Dewey name must mean it's something like 13B-2 (since 390mm is 15.5in) but that's 3*30kg = 90kg, a lot higher than stated.  And even if we derate by a factor 0.7, we get 63kg, as opposed to the 56kg in Dewey's table.

So, could the frame weigh 7kg?  That doesn't seem outlandish to me, but I've never seen one in person.  (Frankly, the photo makes me think more like 1 to 3 kg.)

An idea: possibly Dewey derated more than this factor of 0.7 that's stated above.  Using 0.65 gives 58.5kg, and then a frame of 2.5kg could match the numbers.

Obviously I'm just thinking out loud here.  (This is what @clayton33 and @richardsc would call blackboard talk).

PS. From fresh water to salt water should only be a 2 to 3% change, so that's not it.

**Comment by FormulaFunRacing** [comment]
I think the de-rating is for the depth rating (over long term deployments).  Typically, these floats (and other trawl floats) are deployed for a few hours.  During longer deployments (like on moorings), plastic can slowly deform over time and reach a point of failure.  So, these floats should be de-rated (for depth) for long term deployments.  The plastic used on these Japanese floats is 'harder' than the usual trawl floats sourced locally (Iceplast, SAEplast, etc).  For the 12B-3, I don't use them for depths >200m.

So, like you, I'm a bit doubtful that the frame or (likely) rod assembly is that heavy.  A simple DIA 3/8" X 4' round bar with hardware in seawater is < 1 kg.

Hmmm...

**Comment by richardsc** [comment]
Classic Jay -- using wine implements to demonstrate science to your kid 😄 . Did you have to make sure the bottle was empty first?

Your wife sent me this photo of you looking at the sun:
![image](https://user-images.githubusercontent.com/233584/121556242-18c49a00-c9ea-11eb-9878-190cf2086b6c.png)

**Comment by FormulaFunRacing** [comment]
😂 I had to empty all 12 bottles...all in the name of science!  That’s a
great photo. I could see the eclipse at first, but then it just became a
blur.  I wanted to tweet my experience, but...

Fathers’ Day is coming...I suspect I’ll be on the cover of a popular
publication.  😄
