### ISSUE TITLE
request: meaning of columns in excel file

### ISSUE THREAD

**Issue by dankelley** [dankelley/mooring#29]
I'm a bit lost here as to what columns mean.  From prior help kindly provided by @formulafunracing, I think I know what `DRAG-T` and `DRAG-N` mean, i.e. `DRAG-N` is a drag coefficient, *CD*, in a formula *drag = 0.5 x CD x area x speed^2*  .... but is that the formula intended, or is the 0.5 not used in the formula?  (There are two ways of writing the formula.  I have quoted the one normally used for solid objects, but since this package is getting more complete, I do need to be a bit more sure on factors of 2).

But when it gets to the other columns, I have quite a few head-scratchers.

* columns C and F are both marked as lengths, and they are not equal.  (I think I take column C and multiply by column G to get frontal area for drag computations, but I'm also curious about what column F means.  Perhaps it's a length in the other direction?)
* And there are two area-related columns (G and I).  (Again, I think I use G with C to get the area for drag computation.  If that's the case, I probably don't need to know what column I means.)
* For buoyancy, I see three possibilities: column D is marked in pounds, and column E is marked in Newtons ... which would be fine, but the numbers don't matchup up.  So, I am sort of guessing I should get buoyancy by multiplying the C length column by the H column, to get Newtons. Is that right?

Basically, if it's possible, I'd really love to get a sentence on the meaning of each column.  I need this because the package is getting to the point of actually being useful, say within a few weeks.

I realize that this is a hassle for @formulafunracing, but I don't quite know how else I can figure these things out.

If you can help, @formulafunracing (or other BIO colleagues watching this project), I'd really appreciate it.  There's no huge rush on this, since it's just a fun little side project. Certainly, for the teaching side, I already have all I want.  My goal there is to explain about forces and to give them a basic idea of knockdown issues.

<img width="1204" alt="Screen Shot 2021-06-11 at 6 11 02 AM" src="https://user-images.githubusercontent.com/99469/121662527-d51a7080-ca7b-11eb-9540-40a0d0a944c6.png">

**Comment by dankelley** [comment]
From a note that @formulafunracing just made at #28, I infer that `LBS` is "pound force" as described at https://en.wikipedia.org/wiki/Pound_(force), sometimes abbreviated "lbf" and with conversion 1 lbf=4.448N.

Whoa, it's been a long time since I've thought about pound force.  (Back in 70s, we had to learn the English system, the cgs system, and the SI system.  I think I remember high school assignment questions where  some variables were in English, others in cgs, others in SI. Luckily we had April Wine concerts to erase those numbers from our heads.)

**Comment by FormulaFunRacing** [comment]
lol.  Because of the American use of the English system for metal materials (bar, rod, pipe, etc), most of my engineering calcs were in Imperial (English) units.  It's still has a bit of an influence on me.

I saw Milli Vanelli in concert.  Those guys can really sing.  "Girl, you know it's true..."

I'll have a look at your last post when I have a moment...interesting...

**Comment by dankelley** [comment]
At this stage, I think I understand the meanings.  As discussed, the table might need a bit of updating, but the issue -- as defined by its title -- has been addressed, and therefore I'll close this.
