### ISSUE TITLE
incorporate BIO data

### ISSUE THREAD

**Issue by dankelley** [dankelley/mooring#6]
I see some points of confusion.  Some relate to the fact that the BIO spreadsheet seems to be designed for human inspection, not automated inspection, so the entries in the cells are sometimes odd (e.g. with text in with the numbers, sometimes).

I am looking first at the 3/16 galvanized case, which is the first line in the BIO file.  The entry under "NEWTONS" is "0.76nt/m" which would convert in Dewey's notation to 0.76/9.8=0.077 (approx) for the buoyancy (which is actually buoyancy/metre for a wire).  But Dewey lists 0.007 for what seems to be the same thing.

This will require some more investigation.  The screenshot below shows some evidence.  The top (with yellow) shows the spreadsheet, and the bottom is a text editor with (top) my code, with comments on this case, (middle) the csv I get from Dewey's files and (bottom) output from my reading of the bio data.

Possibly (a) I'm reading Dewey wrong or (b) the BIO table is not correct in this entry.

<img width="756" alt="Screen Shot 2021-05-28 at 9 22 58 AM" src="https://user-images.githubusercontent.com/99469/119983679-d84f3000-bf96-11eb-8fa7-d2236503b5ab.png">

**Comment by dankelley** [comment]
An obvious hint is that the two results differ by about 10, i.e. a factor of g=9.8m/s^2 might be misapplied.  Frankly, my intuition is that I'm doing Dewey's case wrong.  Can a wire weight only 8 grams per metre?  That seems nuts...

**Comment by dankelley** [comment]
I added 2 bio wire types and all but 1 of the bio float types.  (I'm guessing that the colour coding means that the things I called floats are floats.). I had to make guesses on both, and I'm particularly uncertain about the floats, because the excel sheet did not explain things in depth.  Anyway, this is done in "develop", for what it's worth.  (I think the Dewey data are much, much, more reliable because he got them from a book, as I understand it, and authors tend to explain things in some detail.)

I'll look at some of the other things later.

**Comment by dankelley** [comment]
I think I'll do BIO releases today or tomorrow. They are the gray things in the snapshot (i.e. the ones I've highlighted with the dashed lines).  They are not terribly important to drag computations; the only real effect will be their height.

I am pretty sure the area I want is the product of the first LENGTH (col C) and the A (col G).  The other area thing (col I) is maybe the endcap area (just guessing).

<img width="961" alt="Screen Shot 2021-05-29 at 12 23 17 PM" src="https://user-images.githubusercontent.com/99469/120075690-b037fd80-c078-11eb-9acd-61eb22761550.png">

**Comment by dankelley** [comment]
Six BIO releases added (except the one with missing area); see https://dankelley.github.io/mooring/reference/release.html.  I won't go into the details of how I calculated things since I now put those in `create_data/bio/README.Rmd` and will try to document the steps (and guesses) like that for all future additions.

**Comment by dankelley** [comment]
Should add instruments, as in the snapshot (lines 20 to 36).

<img width="1198" alt="Screen Shot 2021-05-30 at 11 12 54 AM" src="https://user-images.githubusercontent.com/99469/120107599-04ee7d80-c138-11eb-875e-9bc980664fb7.png">

**Comment by dankelley** [comment]
Instruments have been added to both `develop` and `main` branches; see list at
https://dankelley.github.io/mooring/articles/mooring_elements.html#instrument-characteristics-1

**Comment by dankelley** [comment]
The final thing left in the BIO excel file is the green group shown below.  I'll add that.  The question is what to call these things.  I don't really want to have a guessing-game of items.  Dewey calls such things `chains` and so I may put them there.

As usual, I don't fully understand the table.  For example, row 11 seems to be talking generally about chain in col B, but a length is listed in col C.  Maybe they always use 1-metre worth of this thing, and that's a length and weight can be listed?  (Where this matters is whether I let the user specify of length of this item, as I do for wires.). However, my first goal is just to get the data into the package; I can figure out exactly what it means, later, perhaps with advice from BIO folks.

Oh, and also, the first 4 things don't have length or area listed, so I'll give them zero length and zero area -- in other words, they will contribute weight, but not drag.

<img width="1172" alt="Screen Shot 2021-05-31 at 7 18 12 AM" src="https://user-images.githubusercontent.com/99469/120179502-0aec6900-c1e1-11eb-87ec-372ccb07b12e.png">

**Comment by dankelley** [comment]
The chains are now added in both the `develop` and `main` branches.  You can see the BIO ones merged in with the Dewey ones, at the doc page https://dankelley.github.io/mooring/articles/mooring_elements.html#chain-characteristics-1

**Comment by dankelley** [comment]
I believe that `mooring` now has all the BIO data that were provided to me. 

I would not claim the data to be stable, though, because e.g. I might be convinced that my decision to convert names to all lower-case ought to be changed.  For example, "eg&g" is an acronym and so perhaps EG&G would be more sensible.  However, then we get into decisions like whether to change "sl" to "SL" -- does that mean single-link or something??

Also, and more generally, I am not too keen on the fact that some names use `"` for inch, others use `in`, and others have no indication of the unit.  I'm torn between
1. pattern names on sources
2. make alterations to names for consistency

If others have thoughts on this decision on naming, which will affect Dewey data as well as BIO data, please let me know.

I will keep this issue open for a few days.

**Comment by richardsc** [comment]
Re the chain discussion in https://github.com/dankelley/mooring/issues/6#issuecomment-851390895 , I think you might be right that the 5/8" galvanized chain is just always used in 1m segments. @clayton33 or I can check that for sure, but it might make sense to consider that someone might use a longer length and treat it as something that can be defined.

**Comment by dankelley** [comment]
@clayton33 and @richardsc -- any thoughts on this issue of whether to make names more uniform with respect to `"` vs `in` vs (nothing)?  Frankly, it's hard to type a quote within a quote, and so I don't like having them.  That would argue to change them all to `in`, perhaps.  However, I think by context, any reader will know that "3/16" refers to 3/16-ths of an inch.  That's common in a hardware store.  

Therefore, my inclination is to remove both `"` and `in` from all names.  What do you think of that?  (The downside is that I'll be changing Dewey's names, but his names are not even consistent -- see snapshot.)

<img width="543" alt="Screen Shot 2021-05-31 at 8 33 44 AM" src="https://user-images.githubusercontent.com/99469/120187259-f4e3a600-c1ea-11eb-9ed7-026e3f19c953.png">

**Comment by richardsc** [comment]
I agree at least with removing `"`. Somehow it feels wrong to have no units, even if it is is standard to just write e.g. 3/8. So I think I argue for leaving `in`. Some future component might be specified in mm, or cm, in the name.

**Comment by dankelley** [comment]
Thanks. Do you think it might look strange to have `"3/16in something"` and also `"3/8 something"`, in adjacent rows?

NOTE: I have not yet coded to prevent name conflicts as I ingest data.  I ought to do that!

**Comment by richardsc** [comment]
I think I would make everything consistent, either `"3/16in something"` or `"3/16 something"`. Honestly, seeing them together I don't have strong feelings one way or the other about the `in` -- consistency is probably more important.

**Comment by dankelley** [comment]
I'm closing this, because the goal (as expressed in the issue title) has been accomplished.  Of course, if we get access to new data (or if access to these data is rescinded) we ought to have new issue(s).
