### ISSUE TITLE
Include depth (and time?) varying flow

### ISSUE THREAD

**Issue by richardsc** [dankelley/mooring#7]
Maybe the time varying flow part of this should be a different issue, but the spirit is the same -- allow the model to run for non-uniform currents, i.e. for u(z)/v(z).

**Comment by dankelley** [comment]
Sorry for the delay in replying.  I was focussing on other things, but this morning I'm clearing up some bugs in the package.  I'll enumerate things.

1. The model allows for depth-varying flow.  The app does not, although it could.  A challenge is how to let the user specify that, with a GUI.  I guess there could be a tab on setup, and in that there could be a bunch of possible functions for depth-dependent flow.  However, I could see this getting into a lot of coding, and I don't need it for my teaching purposes, so a PR from someone with such features might be the way to progress.
2. I see you wrote u(z)/v(z).  Now, the model only has unidirectional flow.  That could be extended without much difficulty, but I'm not really too sure of the purpose.  (Can we verify this for moorings?  I see how we could verify a presumed 2D mooring shape, using pressure sensors, but I'm not sure what measurements could support 3D predictions.). 
3. I think Richard Dewey's code permits x-y velocity components, and also a z velocity component, but I'm not too sure when this would come up.  Maybe with a mooring near very steep topography?  But e.g. coastal upwelling speeds are of order 1e-4 m/s, which gives drag force on e.g. a float of area 1m^2 that is under 1e-5, i.e. much smaller than buoyancy force for a float.  I don't see the point of including a z component.
4. The model is not solving for time.  It assumes force balance, so no acceleration and thus no motion. However, it can follow time-varying currents, in a quasi-steady way, just by repeated calls with different velocity models. This is very simple in code, although trying to get it into `app()` would again be a lot of GUI for the possibilities (does it vary linearly in time, sinusoidally, etc. and with what parameters ... and is velo a product of a function of space and a function of time, or is it an intermingled function).

I am hoping to avoid issues dragging on for too long, so if you (@richardsc or others who I think are following this repo) have comments, or want a quick Z to go over these points, please let me know.

**Comment by dankelley** [comment]
App now has a few depth-varying flows in a pulldown menu.  (The interface is a bit crowded, but I won't worry about that now, while new things are being added.)

<img width="521" alt="Screen Shot 2021-06-03 at 4 57 22 PM" src="https://user-images.githubusercontent.com/99469/120704515-0fd54500-c48d-11eb-9e9c-48fe86891e38.png">

**Comment by richardsc** [comment]
Thanks! 

I think that having u(z) is good enough for now, considering there aren’t any use cases yet that require u+v. 

I’ll try the app!

**Comment by dankelley** [comment]
I'll close this, since it's been addressed and (I think) discussed in a Z call.
